/*  * setupTests (autogenerated)
    * Author : Aden Aziz Hasnayakin
    * Created at: Jum'at, 04 Desember 2020 - 10:49 WIB
*/

// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';
